// #pragma message "Using custom config"

// #define WAIT_FOR_SERIAL 2000

// #define APB_HEATER_TEMPERATURE_AVERAGE_COUNT 1

// #undef APB_AMBIENT_TEMPERATURE_SENSOR_SHT30
// #define APB_AMBIENT_TEMPERATURE_SENSOR_SHT4x

#define INFLUXDB_URL "http://sirius.lan:8086"
#define INFLUXDB_TOKEN "GuXyyAx5tXh66uvT5K7ap3VeIlsTNh5rZ0wPbJaZioNINT-5iSo_gL54U8d5F1oNKOW9bp1DDU1KV1wiisl8SQ=="
#define INFLUXDB_ORG "0d19837b81f9b7e1"
#define INFLUXDB_BUCKET "astropowerbox"


// Prototype
#ifdef CONFIGURATION_FOR_PROTOTYPE
// #pragma message "Prototype configuration"
#undef APB_NETWORK_LOGGER_BACKLOG
#define APB_NETWORK_LOGGER_BACKLOG 50

// #define USE_INFLUXDB
#define ALLOW_ALL_CORS

#undef APB_STATUS_LED_INVERT_LOGIC
#define APB_STATUS_LED_INVERT_LOGIC true

#undef APB_POWER_MAX_CURRENT_AMPS
#define APB_POWER_MAX_CURRENT_AMPS 3.2
#undef APB_POWER_SHUNT_OHMS
#define APB_POWER_SHUNT_OHMS 0.1

#undef APB_AMBIENT_TEMPERATURE_SENSOR_SHT4x
#define APB_AMBIENT_TEMPERATURE_SENSOR_SHT30

#undef APB_HISTORY_TASK_SECONDS 
#define APB_HISTORY_TASK_SECONDS 1'000

#define APB_LOGGER_TX 5
#define APB_LOGGER_RX 6

#undef APB_DATALOGGER
#define APB_DATALOGGER APB_DATALOGGER_SD
#define APB_SD_CS 0

#endif


#ifdef CONFIGURATION_FOR_C11
#undef APB_AMBIENT_TEMPERATURE_SENSOR_SHT4x
#define APB_AMBIENT_TEMPERATURE_SENSOR_SHT30
#endif

#ifdef CONFIGURATION_FOR_ESPRIT100
#endif

#ifdef CONFIGURATION_FOR_STELLALYRA_200
// #undef APB_NETWORK_LOGGER_BACKLOG
// #define APB_NETWORK_LOGGER_BACKLOG 100


#endif


#ifdef CONFIGURATION_FOR_TRAVEL_1
#endif

#ifdef CONFIGURATION_FOR_POWERMONITOR
// #define USE_INFLUXDB
#undef APB_POWER_SHUNT_OHMS
#define APB_POWER_SHUNT_OHMS 0.020
#undef APB_POWER_MAX_CURRENT_AMPS
#define APB_POWER_MAX_CURRENT_AMPS 16

#undef APB_DATALOGGER
#define APB_DATALOGGER APB_DATALOGGER_SD
#define APB_SD_CS 0
// #define APB_SD_CS 7

// #define APB_SPI_MISO 5
// #define APB_SPI_MOSI 6

// #define APB_SPI_CLK 4

#undef APB_PWM_OUTPUTS_PWM_PINOUT
#define APB_PWM_OUTPUTS_PWM_PINOUT
#undef APB_PWM_OUTPUTS_SIZE
#undef APB_PWM_OUTPUTS_TEMP_SENSORS
#define APB_PWM_OUTPUTS_SIZE 0
#define APB_PWM_OUTPUTS_TEMP_SENSORS 0

#undef APB_AMBIENT_TEMPERATURE_SENSOR_SHT4x
#define APB_AMBIENT_TEMPERATURE_SENSOR_NONE

#undef APB_STATUS_LED_INVERT_LOGIC
#define APB_STATUS_LED_INVERT_LOGIC true
#define BOOT_DELAY 2000

#endif

#ifdef CONFIGURATION_FOR_POWERMONITOR_PD
#undef APB_PWM_OUTPUTS_PWM_PINOUT
#define APB_PWM_OUTPUTS_PWM_PINOUT
#undef APB_PWM_OUTPUTS_SIZE
#undef APB_PWM_OUTPUTS_TEMP_SENSORS
#define APB_PWM_OUTPUTS_SIZE 0
#define APB_PWM_OUTPUTS_TEMP_SENSORS 0

#undef APB_AMBIENT_TEMPERATURE_SENSOR_SHT4x
#define APB_AMBIENT_TEMPERATURE_SENSOR_NONE

#undef APB_STATUS_LED_INVERT_LOGIC
#define APB_STATUS_LED_INVERT_LOGIC true
// #define WIFI_POWER_TX WIFI_POWER_11dBm
// #define WIFI_POWER_RX WIFI_POWER_TX
//#define BOOT_DELAY 2000

#endif

#ifdef CONFIGURATION_FOR_XL_1
#undef APB_PWM_OUTPUTS_PWM_PINOUT
#define APB_PWM_OUTPUTS_PWM_PINOUT {4,0, Heater},{3,1, Heater},{5,-1, Output},{20,-1, Output},{21,-1, Output},{2,-1, Output}
#undef APB_PWM_OUTPUTS_SIZE
#define APB_PWM_OUTPUTS_SIZE 6

#undef ONEBUTTON_USER_BUTTON_1
#define ONEBUTTON_USER_BUTTON_1 7

#undef MAX_EVENTS_SIZE
#define MAX_EVENTS_SIZE 1500
#endif

#ifdef CONFIG_PINOUT_WROOM_V1
#undef APB_NETWORK_LOGGER_BACKLOG
#define APB_NETWORK_LOGGER_BACKLOG 100
#endif
