#ifndef APB_CONFIGURATION_H
#define APB_CONFIGURATION_H

#define __APB__SIM 0

#define __APB__SHT30 1
#define __APB__BME280 2
#define __APB__DHT11 3

#define __APB__THERMISTOR 10

#ifdef ARDUINO_LOLIN_S2_MINI
#include "configuration_lolin_s2_mini.h"
#endif

#ifdef ARDUINO_LOLIN_C3_MINI
#include "configuration_lolin_c3_mini.h"
#endif


#define APB_MAX_STATIONS 5
#define APB_AMBIENT_UPDATE_INTERVAL_SECONDS 5
#define APB_HEATER_UPDATE_INTERVAL_SECONDS 5
#define APB_AMBIENT_TEMPERATURE_SENSOR_SHT30_ADDRESS 0x44
#define APB_HEATER_TEMPERATURE_AVERAGE_COUNT 10
#define APB_HEATER_TEMPERATURE_SENSOR_THERMISTOR_REFERENCE 10'000
#define APB_HEATER_TEMPERATURE_SENSOR_THERMISTOR_NOMINAL 10'000
#define APB_HEATER_TEMPERATURE_SENSOR_THERMISTOR_NOMINAL_TEMP 25
#define APB_HEATER_TEMPERATURE_SENSOR_THERMISTOR_B_VALUE 3950
#define APB_POWER_MAX_CURRENT_AMPS 15
#define APB_POWER_SHUNT_OHMS 0.040
#define APB_AMBIENT_TEMPERATURE_SENSOR __APB_SHT30
#define APB_HEATER_TEMPERATURE_SENSOR __APB_THERMISTOR
#define APB_INA1219_ADDRESS 0x40

// #if __has_include ("configuration_custom.h")
#include "configuration_custom.h"
// #endif



// Derivative constants, DO NOT change/redefine


#if APB_HEATER_TEMPERATURE_SENSOR == __APB__SIM
#define APB_HEATER_TEMPERATURE_SENSOR_SIM
#elif APB_HEATER_TEMPERATURE_SENSOR == __APB__THERMISTOR
#define APB_HEATER_TEMPERATURE_SENSOR_THERMISTOR
#else
#error APB_HEATER_TEMPERATURE_SENSOR undefined. Please change configuration_custom.h
#endif

#if APB_AMBIENT_TEMPERATURE_SENSOR == __APB__SIM
#define APB_AMBIENT_TEMPERATURE_SENSOR_SIM
#elif APB_AMBIENT_TEMPERATURE_SENSOR == __APB__SHT30
#define APB_AMBIENT_TEMPERATURE_SENSOR_SHT30
#elif APB_AMBIENT_TEMPERATURE_SENSOR == __APB__BME280
#define APB_AMBIENT_TEMPERATURE_SENSOR_BME280
#elif APB_AMBIENT_TEMPERATURE_SENSOR == __APB__DHT11
#define APB_AMBIENT_TEMPERATURE_SENSOR_DHT11
#else
#error APB_AMBIENT_TEMPERATURE_SENSOR undefined. Please change configuration_custom.h
#endif

#endif
